name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-test:
    runs-on: macos-14
    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      CMAKE_BUILD_PARALLEL_LEVEL: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: microsoft/vcpkg-action@v1

      - name: Install dependencies
        run: |
          echo "Using vcpkg manifest"

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-osx -DBUILD_TESTING=ON -DCMAKE_TOOLCHAIN_FILE="${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build --parallel

      - name: Run unit tests
        run: ctest --test-dir build --output-on-failure

      - name: Clang-Format check
        run: |
          brew update
          brew install clang-format || true
          FILES=$(git ls-files '*.h' '*.hpp' '*.cpp' '*.cc')
          echo "$FILES" | xargs -I {} bash -c "diff -u <(cat '{}') <(clang-format -style=file '{}')" || (echo 'clang-format check failed'; exit 1)

      - name: Clang-Tidy
        run: |
          brew install llvm jq || true
          # Generate compile_commands.json for tidy
          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_TOOLCHAIN_FILE="${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
          # Resolve clang-tidy path (Homebrew or system)
          CLANG_TIDY="$(brew --prefix llvm)/bin/clang-tidy"
          if [ ! -x "$CLANG_TIDY" ]; then CLANG_TIDY="clang-tidy"; fi
          # Run clang-tidy on files from compile_commands.json (non-blocking on failures)
          if [ ! -f build/compile_commands.json ]; then
            echo "compile_commands.json not found; skipping clang-tidy"
            exit 0
          fi
          FILES=$(jq -r '.[].file' build/compile_commands.json | grep -E '\.(cpp|cc|cxx)$' | sort -u)
          if [ -z "$FILES" ]; then
            echo "No C/C++ source files found for clang-tidy"
            exit 0
          fi
          echo "$FILES" | xargs -I {} bash -lc '"$0" "{}" --quiet --config-file=.clang-tidy -p=build' "$CLANG_TIDY" || echo 'clang-tidy step non-blocking'
